### ISSUE TITLE
source for rg-card

### ISSUE THREAD

**Issue by jahbini** [riotgear2/rg#3]
i am trying to use the rg-card riot tag as described at https://riotgear2.github.io/components/cards/

The 'source link' on that page points to this repository.  unfortunately there is no source for rg-card here.

Where is it found/

**Comment by adavie1** [comment]
Thanks for the feedback. I'll sort that out shortly. You can [view rg.js](https://github.com/riotgear2/rg/blob/master/dist/rg.js) which has the source of all the components.
At some point I'll break them out to individual components as the original RG v1 does.
