### ISSUE TITLE
Source files for rg2 tags

### ISSUE THREAD

**Issue by casscauley** [riotgear2/rg#5]
Hello! I'm the guy from the main riot gear repo who wants to take it over. I just pulled the code for this repo and I'm not seeing any source files. All the riot tags for this repo only exist in the dist folder, which gets wiped when I run the build script. Do you have the source files? I can un-compile them pretty easily if not.

**Comment by casscauley** [comment]
@adavie1 I finally got ahold of the creator of RiotGear and it sounds like he no longer has control of that org/account. I'm going to try to publish my updates as rg3 (and eventually rg4) as a nod to the version of riot they are compatible with. Hopefully I can get that out this weekend.

**Comment by adavie1** [comment]
@chriscauley when I started this, I was very clueless about developing in JS. So It's all in the rg.min.js. This month I am crazy busy, so I won't be able to extract them to source files. I had intended to do that. I'm very busy with VueJS projects these days, so that will help formatting the RiotJS stuff. Conversely working with RiotJS helped pick up VueJS :-P

**Comment by casscauley** [comment]
I figured as much but just wanted to check. I'm in the opposite boat as you: I started with riot, switched to react and vue for a year, and now want to get back into riot. 

But any how, I'm going to close this. I invite you to follow https://github.com/chriscauley/rg if you're curious to see what I do with it. My biggest goal is to make all the css classes dynamic so that the library will work with bootstrap, materialize and other css frameworks. I'm basing this off of some work I did (in a private repo) with React, so it'll generalize to Vue or anything else quite nicely.

**Comment by adavie1** [comment]
@chriscauley I had the same idea- to make components that would be easy to transport from framework to framework.
I can add you as an owner to both this repo and the original rg repo.

**Comment by casscauley** [comment]
Good to hear that you have control over the original repo. I emailed the previous owner and he said he didn't have access, so I was starting to worry it might be lost forever. I still think it's wise to release this on npm as `rg3` and eventually `rg4` as I plan to support riot 3 for at least a year. 

If you give me access I'll still create PRs so you can vet changes, but no expectation on time commitment.

On my repo I have a branch for riot3 which I believe is complete. It also expands test coverage to 100% (which sounds unnecessary but I found bugs at almost every step of the way). Unfortunately I have to run to work, but I'll put a PR up tonight. If you want to play with it, I've updated CONTRIBUTING.md a bit with more clear instructions on how to develop code. No expectations, though, I know you said you're busy.

https://github.com/chriscauley/rg/blob/riot3/CONTRIBUTING.md

**Comment by adavie1** [comment]
@chriscauley added you as a collaborator on both this repo and the orginal RG repo.
